In [1]:
import automech
from IPython.display import display

In [2]:
inp = "cyclopentene_chem.inp"
spc_inp = "cyclopentene_species_dictionary.txt"

inp = "12epoxycyclopentane_chem.inp"
spc_inp = "12epoxycyclopentane_species_dictionary.txt"

inp = "13epoxyCPT_chem.inp"
spc_inp = "13epoxyCPT_species_dictionary.txt"

out = inp.replace("_chem.inp", "_reactions.csv")
spc_out = spc_inp.replace("species_dictionary.txt", "species.csv")

print("Reading in mechanism:")
mech = automech.io.rmg.read.mechanism(
    inp=inp, spc_inp=spc_inp, out=out, spc_out=spc_out
)
display(mech.species)
display(mech.reactions)

  0%|          | 0/345 [00:00<?, ?it/s]

,name,spin,charge,chi,smi
0,N2,1,0,InChI=1S/N2/c1-2,N#N
1,Ar,1,0,InChI=1S/Ar,[Ar]
2,He,1,0,InChI=1S/He,[He]
3,Ne,1,0,InChI=1S/Ne,[Ne]
4,C5H7O(1),2,0,"InChI=1S/C5H7O/c1-2-5-3-4(1)6-5/h3-5H,1-2H2",O1C2CCC1[CH]2
...,...,...,...,...,...
340,S(613),2,0,"InChI=1S/C5H7O3/c6-4-2-1-3-5(4)8-7/h1,3-5,7H,2H2",OOC1C([O])CC=C1
341,C5H7O(377),2,0,"InChI=1S/C5H7O/c1-2-3-4-5-6/h3,5H,2H2,1H3",[O]C=C=CCC
342,C5H7O(212),2,0,"InChI=1S/C5H7O/c1-4-6-5(2)3/h1,4H,2H2,3H3",CC(OC=[CH])=C
343,C5H7O(447),2,0,"InChI=1S/C5H7O/c1-2-6-5-3-4-5/h2-3,5H,1,4H2",C=COC1C[CH]1
344,S(469),2,0,"InChI=1S/C5H7O3/c1-2-3-5(4-6)8-7/h2,5,7H,1,3H2",OOC(CC=C)[C]=O

,eq,rate
0,C5H7O(1) = C5H7O(3),SimpleRate(k=ArrheniusFunction(A=145000000000....
1,C5H7O(1) = C5H7O(2),"SimpleRate(k=ArrheniusFunction(A=1468000.0, b=..."
2,C5H7O(2) = C5H7O(3),SimpleRate(k=ArrheniusFunction(A=72500000000.0...
3,C5H7O(2) = C5H7O(3),"SimpleRate(k=ArrheniusFunction(A=7669944000.0,..."
4,C5H7O(2) = C5H7O(3),SimpleRate(k=ArrheniusFunction(A=72500000000.0...
...,...,...
696,C5H7O(481) = C5H7O(447),"SimpleRate(k=ArrheniusFunction(A=960400000.0, ..."
697,S(469) = S(427),"SimpleRate(k=ArrheniusFunction(A=0.005045394, ..."
698,S(469) = S(342),"SimpleRate(k=ArrheniusFunction(A=94700000.0, b..."
699,HO2(77) + C5H6O(361) = S(469),"SimpleRate(k=ArrheniusFunction(A=698.5928, b=2..."
700,S(470) = S(469),"SimpleRate(k=ArrheniusFunction(A=128600000.0, ..."